// auto generated by c2z
const std = @import("std");
//const cpp = @import("cpp");

/// An assertion failure function.
///  @param[in] expression   asserted expression.
///  @param[in] file   Filename of the failed assertion.
///  @param[in] line   Line number of the failed assertion.
///  @see rcAssertFailSetCustom
pub const rcAssertFailFunc = fn ([*c]const u8, [*c]const u8, c_int) callconv(.C) void;

extern fn _1_rcAssertFailSetCustom_(assertFailFunc: [*c]rcAssertFailFunc) void;
/// Sets the base custom assertion failure function to be used by Recast.
///  @param[in] assertFailFunc     The function to be used in case of failure of #dtAssert
pub const rcAssertFailSetCustom = _1_rcAssertFailSetCustom_;

extern fn _1_rcAssertFailGetCustom_() [*c]rcAssertFailFunc;
/// Gets the base custom assertion failure function to be used by Recast.
pub const rcAssertFailGetCustom = _1_rcAssertFailGetCustom_;
